# Generated by Django 5.1.3 on 2024-11-21 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("contact_email", models.EmailField(max_length=254, unique=True)),
                ("location", models.CharField(max_length=100)),
                ("website", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="candidate",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AddField(
            model_name="candidate",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.employer",
            ),
        ),
    ]
